name: Advent of Code 2019 in Rust 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -r
    - name: Run days
      run: |
        cargo run --bin day1 inputs/input1.txt
        cargo run --bin day2 inputs/input2.txt
        cargo run --bin day3 inputs/input3.txt
        cargo run --bin day4
        cargo run --bin day5 inputs/input5.txt
        cargo run --bin day6 inputs/input6.txt
        cargo run --bin day7 inputs/input7.txt
        cargo run --bin day8
        cargo run --bin day9
