name: Advent of Code 2019 in Rust 

on:
  push:
    branches: [ "main" ]
    paths:
      - "2019/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "2019/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --bin aoc2019
    - name: Run tests
      run: cargo test --release --bin aoc2019

