name: Advent of Code 2024 in Rust 

on:
  push:
    branches: [ "main" ]
    paths:
      - "Rust/2024/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "Rust/2024/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --bin aoc2024
      working-directory: Rust
    - name: Run tests
      run: cargo test --release --bin aoc2024
      working-directory: Rust

